export interface Comuna {
  id: string;
  name: string;
}

export interface Region {
  id: string;
  name: string;
  shortName: string;
  romanNumeral: string;
  comunas: Comuna[];
}

// In Cuba: "Region" = Provincia, "Comuna" = Municipio.
// We keep the original interface names so the rest of the codebase
// (filters, forms, URLs, DB columns) doesn't need to change.
// `romanNumeral` is repurposed as a short provincial badge code.

export const regions: Region[] = [
  {
    id: "pinar-del-rio",
    name: "Pinar del Río",
    shortName: "Pinar del Río",
    romanNumeral: "PRI",
    comunas: [
      { id: "pinar-del-rio", name: "Pinar del Río" },
      { id: "consolacion-del-sur", name: "Consolación del Sur" },
      { id: "guane", name: "Guane" },
      { id: "la-palma", name: "La Palma" },
      { id: "los-palacios", name: "Los Palacios" },
      { id: "mantua", name: "Mantua" },
      { id: "minas-de-matahambre", name: "Minas de Matahambre" },
      { id: "san-juan-y-martinez", name: "San Juan y Martínez" },
      { id: "san-luis", name: "San Luis" },
      { id: "sandino", name: "Sandino" },
      { id: "vinales", name: "Viñales" },
    ],
  },
  {
    id: "artemisa",
    name: "Artemisa",
    shortName: "Artemisa",
    romanNumeral: "ART",
    comunas: [
      { id: "artemisa", name: "Artemisa" },
      { id: "alquizar", name: "Alquízar" },
      { id: "bauta", name: "Bauta" },
      { id: "bahia-honda", name: "Bahía Honda" },
      { id: "caimito", name: "Caimito" },
      { id: "candelaria", name: "Candelaria" },
      { id: "guanajay", name: "Guanajay" },
      { id: "guira-de-melena", name: "Güira de Melena" },
      { id: "mariel", name: "Mariel" },
      { id: "san-antonio-de-los-banos", name: "San Antonio de los Baños" },
      { id: "san-cristobal", name: "San Cristóbal" },
    ],
  },
  {
    id: "la-habana",
    name: "La Habana",
    shortName: "Habana",
    romanNumeral: "HAB",
    comunas: [
      { id: "arroyo-naranjo", name: "Arroyo Naranjo" },
      { id: "boyeros", name: "Boyeros" },
      { id: "centro-habana", name: "Centro Habana" },
      { id: "cerro", name: "Cerro" },
      { id: "cotorro", name: "Cotorro" },
      { id: "diez-de-octubre", name: "Diez de Octubre" },
      { id: "guanabacoa", name: "Guanabacoa" },
      { id: "habana-del-este", name: "Habana del Este" },
      { id: "habana-vieja", name: "Habana Vieja" },
      { id: "la-lisa", name: "La Lisa" },
      { id: "marianao", name: "Marianao" },
      { id: "playa", name: "Playa" },
      { id: "plaza-de-la-revolucion", name: "Plaza de la Revolución" },
      { id: "regla", name: "Regla" },
      { id: "san-miguel-del-padron", name: "San Miguel del Padrón" },
    ],
  },
  {
    id: "mayabeque",
    name: "Mayabeque",
    shortName: "Mayabeque",
    romanNumeral: "MAY",
    comunas: [
      { id: "san-jose-de-las-lajas", name: "San José de las Lajas" },
      { id: "batabano", name: "Batabanó" },
      { id: "bejucal", name: "Bejucal" },
      { id: "guines", name: "Güines" },
      { id: "jaruco", name: "Jaruco" },
      { id: "madruga", name: "Madruga" },
      { id: "melena-del-sur", name: "Melena del Sur" },
      { id: "nueva-paz", name: "Nueva Paz" },
      { id: "quivican", name: "Quivicán" },
      { id: "san-nicolas-de-bari", name: "San Nicolás de Bari" },
      { id: "santa-cruz-del-norte", name: "Santa Cruz del Norte" },
    ],
  },
  {
    id: "matanzas",
    name: "Matanzas",
    shortName: "Matanzas",
    romanNumeral: "MTZ",
    comunas: [
      { id: "matanzas", name: "Matanzas" },
      { id: "calimete", name: "Calimete" },
      { id: "cardenas", name: "Cárdenas" },
      { id: "cienaga-de-zapata", name: "Ciénaga de Zapata" },
      { id: "colon", name: "Colón" },
      { id: "jaguey-grande", name: "Jagüey Grande" },
      { id: "jovellanos", name: "Jovellanos" },
      { id: "limonar", name: "Limonar" },
      { id: "los-arabos", name: "Los Arabos" },
      { id: "marti", name: "Martí" },
      { id: "pedro-betancourt", name: "Pedro Betancourt" },
      { id: "perico", name: "Perico" },
      { id: "union-de-reyes", name: "Unión de Reyes" },
    ],
  },
  {
    id: "cienfuegos",
    name: "Cienfuegos",
    shortName: "Cienfuegos",
    romanNumeral: "CFG",
    comunas: [
      { id: "cienfuegos", name: "Cienfuegos" },
      { id: "abreus", name: "Abreus" },
      { id: "aguada-de-pasajeros", name: "Aguada de Pasajeros" },
      { id: "cruces", name: "Cruces" },
      { id: "cumanayagua", name: "Cumanayagua" },
      { id: "lajas", name: "Lajas" },
      { id: "palmira", name: "Palmira" },
      { id: "rodas", name: "Rodas" },
    ],
  },
  {
    id: "villa-clara",
    name: "Villa Clara",
    shortName: "Villa Clara",
    romanNumeral: "VCL",
    comunas: [
      { id: "santa-clara", name: "Santa Clara" },
      { id: "caibarien", name: "Caibarién" },
      { id: "camajuani", name: "Camajuaní" },
      { id: "cifuentes", name: "Cifuentes" },
      { id: "corralillo", name: "Corralillo" },
      { id: "encrucijada", name: "Encrucijada" },
      { id: "manicaragua", name: "Manicaragua" },
      { id: "placetas", name: "Placetas" },
      { id: "quemado-de-guines", name: "Quemado de Güines" },
      { id: "ranchuelo", name: "Ranchuelo" },
      { id: "remedios", name: "Remedios" },
      { id: "sagua-la-grande", name: "Sagua la Grande" },
      { id: "santo-domingo", name: "Santo Domingo" },
    ],
  },
  {
    id: "sancti-spiritus",
    name: "Sancti Spíritus",
    shortName: "S. Spíritus",
    romanNumeral: "SSP",
    comunas: [
      { id: "sancti-spiritus", name: "Sancti Spíritus" },
      { id: "cabaiguan", name: "Cabaiguán" },
      { id: "fomento", name: "Fomento" },
      { id: "jatibonico", name: "Jatibonico" },
      { id: "la-sierpe", name: "La Sierpe" },
      { id: "taguasco", name: "Taguasco" },
      { id: "trinidad", name: "Trinidad" },
      { id: "yaguajay", name: "Yaguajay" },
    ],
  },
  {
    id: "ciego-de-avila",
    name: "Ciego de Ávila",
    shortName: "C. de Ávila",
    romanNumeral: "CAV",
    comunas: [
      { id: "ciego-de-avila", name: "Ciego de Ávila" },
      { id: "baragua", name: "Baraguá" },
      { id: "bolivia", name: "Bolivia" },
      { id: "chambas", name: "Chambas" },
      { id: "ciro-redondo", name: "Ciro Redondo" },
      { id: "florencia", name: "Florencia" },
      { id: "majagua", name: "Majagua" },
      { id: "moron", name: "Morón" },
      { id: "primero-de-enero", name: "Primero de Enero" },
      { id: "venezuela", name: "Venezuela" },
    ],
  },
  {
    id: "camaguey",
    name: "Camagüey",
    shortName: "Camagüey",
    romanNumeral: "CMG",
    comunas: [
      { id: "camaguey", name: "Camagüey" },
      { id: "carlos-manuel-de-cespedes", name: "Carlos Manuel de Céspedes" },
      { id: "esmeralda", name: "Esmeralda" },
      { id: "florida", name: "Florida" },
      { id: "guaimaro", name: "Guáimaro" },
      { id: "jimaguayu", name: "Jimaguayú" },
      { id: "minas", name: "Minas" },
      { id: "najasa", name: "Najasa" },
      { id: "nuevitas", name: "Nuevitas" },
      { id: "santa-cruz-del-sur", name: "Santa Cruz del Sur" },
      { id: "sibanicu", name: "Sibanicú" },
      { id: "sierra-de-cubitas", name: "Sierra de Cubitas" },
      { id: "vertientes", name: "Vertientes" },
    ],
  },
  {
    id: "las-tunas",
    name: "Las Tunas",
    shortName: "L. Tunas",
    romanNumeral: "LTU",
    comunas: [
      { id: "las-tunas", name: "Las Tunas" },
      { id: "amancio", name: "Amancio" },
      { id: "colombia", name: "Colombia" },
      { id: "jesus-menendez", name: "Jesús Menéndez" },
      { id: "jobabo", name: "Jobabo" },
      { id: "majibacoa", name: "Majibacoa" },
      { id: "manati", name: "Manatí" },
      { id: "puerto-padre", name: "Puerto Padre" },
    ],
  },
  {
    id: "holguin",
    name: "Holguín",
    shortName: "Holguín",
    romanNumeral: "HOL",
    comunas: [
      { id: "holguin", name: "Holguín" },
      { id: "antilla", name: "Antilla" },
      { id: "baguanos", name: "Báguanos" },
      { id: "banes", name: "Banes" },
      { id: "cacocum", name: "Cacocum" },
      { id: "calixto-garcia", name: "Calixto García" },
      { id: "cueto", name: "Cueto" },
      { id: "frank-pais", name: "Frank País" },
      { id: "gibara", name: "Gibara" },
      { id: "mayari", name: "Mayarí" },
      { id: "moa", name: "Moa" },
      { id: "rafael-freyre", name: "Rafael Freyre" },
      { id: "sagua-de-tanamo", name: "Sagua de Tánamo" },
      { id: "urbano-noris", name: "Urbano Noris" },
    ],
  },
  {
    id: "granma",
    name: "Granma",
    shortName: "Granma",
    romanNumeral: "GRA",
    comunas: [
      { id: "bayamo", name: "Bayamo" },
      { id: "bartolome-maso", name: "Bartolomé Masó" },
      { id: "buey-arriba", name: "Buey Arriba" },
      { id: "campechuela", name: "Campechuela" },
      { id: "cauto-cristo", name: "Cauto Cristo" },
      { id: "guisa", name: "Guisa" },
      { id: "jiguani", name: "Jiguaní" },
      { id: "manzanillo", name: "Manzanillo" },
      { id: "media-luna", name: "Media Luna" },
      { id: "niquero", name: "Niquero" },
      { id: "pilon", name: "Pilón" },
      { id: "rio-cauto", name: "Río Cauto" },
      { id: "yara", name: "Yara" },
    ],
  },
  {
    id: "santiago-de-cuba",
    name: "Santiago de Cuba",
    shortName: "Stgo. de Cuba",
    romanNumeral: "SCU",
    comunas: [
      { id: "santiago-de-cuba", name: "Santiago de Cuba" },
      { id: "contramaestre", name: "Contramaestre" },
      { id: "guama", name: "Guamá" },
      { id: "mella", name: "Mella" },
      { id: "palma-soriano", name: "Palma Soriano" },
      { id: "san-luis-scu", name: "San Luis" },
      { id: "segundo-frente", name: "Segundo Frente" },
      { id: "songo-la-maya", name: "Songo-La Maya" },
      { id: "tercer-frente", name: "Tercer Frente" },
    ],
  },
  {
    id: "guantanamo",
    name: "Guantánamo",
    shortName: "Guantánamo",
    romanNumeral: "GTM",
    comunas: [
      { id: "guantanamo", name: "Guantánamo" },
      { id: "baracoa", name: "Baracoa" },
      { id: "caimanera", name: "Caimanera" },
      { id: "el-salvador", name: "El Salvador" },
      { id: "imias", name: "Imías" },
      { id: "maisi", name: "Maisí" },
      { id: "manuel-tames", name: "Manuel Tames" },
      { id: "niceto-perez", name: "Niceto Pérez" },
      { id: "san-antonio-del-sur", name: "San Antonio del Sur" },
      { id: "yateras", name: "Yateras" },
    ],
  },
  {
    id: "isla-de-la-juventud",
    name: "Isla de la Juventud",
    shortName: "Isla",
    romanNumeral: "IJV",
    comunas: [
      { id: "nueva-gerona", name: "Nueva Gerona" },
    ],
  },
];

export function getRegionById(id: string): Region | undefined {
  return regions.find((r) => r.id === id);
}

export function getComunaById(regionId: string, comunaId: string): Comuna | undefined {
  const region = getRegionById(regionId);
  return region?.comunas.find((c) => c.id === comunaId);
}
